#exclude: '^(chronobio/)'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
    -   id: mypy
    exclude: ^(?!(notre_ferme/|tests/)).*$
    # args: ["--ignore-missing-imports", "--scripts-are-modules", "notre_ferme", "test"]


-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
